#!/bin/bash
interfaz=$(ip addr | grep -iE "inet *|brd *" | grep -vE "127.0.0.1|inet6"  | grep -oP 'inet \d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}' | awk '{print $2}' | awk 'NR==1' 2>/dev/null)
if [[ "$interfaz" ]]; then
  echo "%{F#1bbf3e}󰖩 %{F#ffffff}$(ip addr | grep -iE "inet *|brd *" | grep -vE "127.0.0.1|inet6"  | grep -oP 'inet \d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}' | awk '{print $2}' | awk 'NR==1' )%{u-}"
else
  echo "%{F#FF4C4C}󱛅 %{F#ffffff}Disconnected"
fi
