#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII  

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

vmware-user-suid-wrapper & 
feh --bg-fill ~/Imágenes/Wallpaper.jpg
~/.config/polybar/./launch.sh &
picom &
#bspc config focused_border_color "#C2F6FC"
#bspc config normal_border_color "#010812"
bspc config border_width 0
