#!/bin/bash
IP_ADDR=$(ip a  | grep -vE '127|172|tun0' | grep -oP "inet \K\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}" 2>/dev/null)
if [[ "$IP_ADDR" ]]; then
  echo "%{F#1bbf3e}󰖩 %{F#ffffff}$IP_ADDR%{u-}"
else
  echo "%{F#FF4C4C}󱛅 %{F#ffffff}Disconnected"
fi
